%NUFFT1D3F90 - 
%
% Syntax:  [fk, ier] = nufft1d3f90(xj, cj, iflag, eps, sk)
%
% Inputs:
%    xj - double (nj,1)
%    cj - complex double (nj,1)
%    iflag - int
%    eps - double
%    sk - double (nk,1)
%
% Outputs:
%    fk - complex double (nk,1)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
