%NUFFT1D2F90 - 
%
% Syntax:  [cj, ier] = nufft1d2f90(xj, iflag, eps, fk)
%
% Inputs:
%    xj - double (nj,1)
%    iflag - int
%    eps - double
%    fk - complex double (ms,1)
%
% Outputs:
%    cj - complex double (nj,1)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
