%NUFFT3D1F90 - 
%
% Syntax:  [fk, ier] = nufft3d1f90(xj, yj, zj, cj, iflag, eps, ms, mt, mu)
%
% Inputs:
%    xj - double (nj,1)
%    yj - double (nj,1)
%    zj - double (nj,1)
%    cj - complex double (nj,1)
%    iflag - int
%    eps - double
%    ms - int
%    mt - int
%    mu - int
%
% Outputs:
%    fk - complex double (ms,mt,mu)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
