%NUFFT1D1F90 - 
%
% Syntax:  [fk, ier] = nufft1d1f90(xj, cj, iflag, eps, ms)
%
% Inputs:
%    xj - double (nj,1)
%    cj - complex double (nj,1)
%    iflag - int
%    eps - double
%    ms - int
%
% Outputs:
%    fk - complex double (ms,1)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
