%NUFFT2D1F90 - 
%
% Syntax:  [fk, ier] = nufft2d1f90(xj, yj, cj, iflag, eps, ms, mt)
%
% Inputs:
%    xj - double (nj,1)
%    yj - double (nj,1)
%    cj - complex double (nj,1)
%    iflag - int
%    eps - double
%    ms - int
%    mt - int
%
% Outputs:
%    fk - complex double (ms,mt)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
